apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: rhcl-sandbox  # Or whatever namespace you deploy Envoy in
  annotations:
    metallb.universe.tf/address-pool: f5-ip-pool
spec:
  type: LoadBalancer
  selector:
    app: envoy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443